//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_joliebakery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Jolie_bakeryEntities1 : DbContext
    {
        public Jolie_bakeryEntities1()
            : base("name=Jolie_bakeryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_HOADON_CHITIET> TBL_HOADON_CHITIET { get; set; }
        public virtual DbSet<TBL_SANPHAM> TBL_SANPHAM { get; set; }
        public virtual DbSet<TBL_HOADON> TBL_HOADON { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
    }
}
