//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_joliebakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Loai { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string CakeName { get; set; }
        public System.DateTime Birthday { get; set; }
        public string MessageCake { get; set; }
        public string CakeType { get; set; }
        public string CakeTaste { get; set; }
        public string AnotherTaste { get; set; }
    }
}
