//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_joliebakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HOADON_CHITIET
    {
        public int IDCTHD { get; set; }
        public string MAHD { get; set; }
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public double GIATIEN { get; set; }
        public int SOLUONG { get; set; }
        public double THANH_TIEN { get; set; }
    }
}
