//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_joliebakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HOADON
    {
        public int IDHD { get; set; }
        public string MAHD { get; set; }
        public string TEN_KHACH_HANG { get; set; }
        public string SDT { get; set; }
        public string DIA_CHI_GIAO_HANG { get; set; }
        public string GHICHU { get; set; }
        public Nullable<double> TONG_THANH_TIEN { get; set; }
        public int TRANG_THAI { get; set; }
        public Nullable<System.DateTime> NGAYBAN { get; set; }
    }
}
